# SITE CONFIGURATION
baseurl: ""
url: "https://amanps.github.io/"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Amanpreet Singh
  avatar: assets/img/avatar.png
  favicon:
  gravatar: # Email MD5 hash
  description: "Amanpreet Singh's website and blog about Software Engineering." # used by search engines

  # Header and footer text
  header_text:
  header_text_feature_image:
  footer_text: >
   Copyright &copy; 2018 Amanpreet Singh &#8226; Powered by the <a href="https://github.com/rohanchandra/type-theme" target="_blank">Type Theme</a>

  # Icons
  rss: false
  email_address: "hi@amanps.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "amanps"
  google_plus:
  instagram:
  linkedin:  "https://www.linkedin.com/in/amanps/"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "multivitaman"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-116678721-1"
  disqus_shortname:
  katex: true # Enable if using math markup
  search: false # Enable the search feature

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
theme: jekyll-theme-type
exclude:
  - Gemfile
  - Gemfile.lock
